apiVersion: apps/v1
kind: Deployment
metadata:
  name: storybook
  labels:
    app: storybook
spec:
  selector:
    matchLabels:
      app: storybook
  template:
    metadata:
      labels:
        app: storybook
        tier: web
    spec:
      containers:
        - name: storybook
          image: storybook
          ports:
            - containerPort: {{ .Values.frontend.storybook.port }}
---
apiVersion: v1
kind: Service
metadata:
  name: storybook
  labels:
    app: storybook
spec:
  ports:
    - port: 80
      targetPort: {{ .Values.frontend.storybook.port }}
      protocol: TCP
  selector:
    app: storybook
