apiVersion: apps/v1
kind: Deployment
metadata:
  name: server
  labels:
    app: server
spec:
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
        - name: server
          command:
            - "/bin/sh"
            - "-c"
            - "/app/server server"
          image: server-image
          ports:
            - containerPort: {{ .Values.server.port }}
          env:
            - name: DB_HOST
              value: {{ .Values.postgresql.fullnameOverride }}
            - name: DB_USER
              value: {{ .Values.postgresql.auth.username }}
            - name: DB_PASSWORD
              value: {{ .Values.postgresql.auth.password }}
            - name: DB_NAME
              value: reacttv
            - name: DB_NAME_POSTGRES
              value: postgres
            - name: JWT_SECRET_KEY
              value: some-random-local-de-secret-key
